
project_id = "vupcbgwmmezxiegfxent"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323
browser_open = false

[inbucket]
port = 54324
storage_backend = "memory"
storage_backend_params = ""

[storage]
file_storage_backend = "file"
file_storage_backend_params = ""

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000", "http://localhost:5173"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = true

[auth.external.github]
enabled = false
client_id = ""
redirect_uri = ""
secret = ""

[functions]
serve_local_functions = true

[functions.whatsapp-messages]
verify_jwt = false
