
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vupcbgwmmezxiegfxent.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1cGNiZ3dtbWV6eGllZ2Z4ZW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzEwNzgsImV4cCI6MjA1NzQwNzA3OH0.NhXm1syK3gG5xC3vhlPHGCbppj6Eq1DJipt2nMlO4wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
